import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZES, TOUCH } from "@/constants/design-tokens";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  header: {
    backgroundColor: COLORS.teal,
    paddingTop: 50,
    paddingBottom: 26,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    shadowColor: COLORS.tealDark,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
    zIndex: 10,
  },
  headerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headerTitle: {
    color: "#fff",
    fontSize: FONT_SIZES.screenTitle,
    fontWeight: "bold",
    marginBottom: 6,
  },
  headerSubtitle: {
    color: "#DDEFEA",
    fontSize: FONT_SIZES.small,
  },
  content: {
    flex: 1,
  },
  view: {
    padding: 16,
    paddingBottom: 40,
  },
  medName: {
    fontSize: FONT_SIZES.medName,
    fontWeight: "bold",
    color: COLORS.tealDark,
    marginVertical: 4,
  },
  medDetail: {
    color: COLORS.inkSoft,
    fontSize: FONT_SIZES.medDetail,
    marginTop: 2,
  },
  medDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  cardHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    minHeight: 48,
  },
  cardExpandedSection: {
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: COLORS.line,
    borderStyle: "dashed",
  },
  emptyBox: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.line,
    borderWidth: 2,
    borderStyle: "dashed",
    borderRadius: 22,
    padding: 30,
    alignItems: "center",
  },
  emptyBoxText: {
    color: COLORS.inkSoft,
    textAlign: "center",
    lineHeight: 24,
    fontSize: FONT_SIZES.helperText,
  },
  formCard: {
    backgroundColor: COLORS.card,
    borderRadius: 22,
    padding: 18,
    borderColor: COLORS.line,
    borderWidth: 1,
    marginTop: 14,
  },
  label: {
    fontWeight: "bold",
    fontSize: FONT_SIZES.formLabel,
    color: COLORS.inkSoft,
    marginBottom: 6,
    marginTop: 14,
  },
  input: {
    backgroundColor: "#fff",
    borderWidth: 1.5,
    borderColor: COLORS.line,
    borderRadius: 14,
    padding: 16,
    fontSize: FONT_SIZES.formLabel,
    color: COLORS.ink,
    minHeight: TOUCH.input,
  },
  errorText: {
    color: COLORS.amberDark,
    fontSize: FONT_SIZES.helperText,
    marginTop: 6,
    fontWeight: "600",
  },
  optionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  optionButton: {
    flex: 1,
    flexDirection: "row",
    gap: 8,
    borderWidth: 1.5,
    borderColor: COLORS.line,
    borderRadius: 14,
    padding: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F9F7F1",
    minHeight: TOUCH.button,
  },
  optionButtonActive: {
    backgroundColor: COLORS.teal,
    borderColor: COLORS.teal,
  },
  optionButtonText: {
    color: COLORS.inkSoft,
    fontWeight: "bold",
    fontSize: FONT_SIZES.formLabel,
  },
  optionButtonTextActive: {
    color: "#fff",
  },
  buttonRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
  },
  smallButton: {
    flex: 1,
    marginTop: 0,
    marginBottom: 0,
    minHeight: TOUCH.button,
  },
  btnPrimary: {
    flexDirection: "row",
    gap: 8,
    backgroundColor: COLORS.teal,
    borderRadius: 16,
    padding: 18,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    minHeight: TOUCH.button,
  },
  btnPrimaryText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: FONT_SIZES.button,
  },
  photoPreview: {
    width: "100%",
    height: 260,
    borderRadius: 14,
    marginTop: 10,
  },
  medPhoto: {
    width: "100%",
    height: 220,
    borderRadius: 14,
    marginVertical: 10,
  },
  btnSecondary: {
    flexDirection: "row",
    gap: 8,
    backgroundColor: COLORS.card,
    borderColor: COLORS.teal,
    borderWidth: 2,
    borderRadius: 16,
    padding: 17,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    marginTop: 10,
    marginBottom: 16,
    minHeight: TOUCH.button,
  },
  btnSecondaryText: {
    color: COLORS.teal,
    fontWeight: "bold",
    fontSize: FONT_SIZES.button,
  },
  btnDangerWrapper: {
    marginTop: 24,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.line,
    borderStyle: "dashed",
  },
  btnDanger: {
    flexDirection: "row",
    gap: 8,
    backgroundColor: COLORS.card,
    borderColor: COLORS.red,
    borderWidth: 2,
    borderRadius: 16,
    padding: 15,
    alignItems: "center",
    justifyContent: "center",
    minHeight: TOUCH.button,
  },
  btnDangerText: {
    color: COLORS.red,
    fontWeight: "bold",
    fontSize: FONT_SIZES.button - 2,
  },
  helperText: {
    color: COLORS.inkSoft,
    fontSize: FONT_SIZES.helperText,
    marginTop: 6,
    lineHeight: 21,
  },
  btnDisabled: {
    backgroundColor: "#F0EEE7",
    borderColor: COLORS.line,
    opacity: 0.7,
  },
  btnDisabledText: {
    color: COLORS.inkSoft,
  },
  chatCard: {
    backgroundColor: COLORS.card,
    borderRadius: 22,
    padding: 16,
    borderColor: COLORS.line,
    borderWidth: 1,
    minHeight: 420,
  },
  chatTitle: {
    fontSize: FONT_SIZES.medName,
    fontWeight: "bold",
    color: COLORS.tealDark,
  },
  chatSubtitle: {
    color: COLORS.inkSoft,
    fontSize: FONT_SIZES.helperText,
    marginTop: 4,
    marginBottom: 12,
  },
  chatMessages: {
    maxHeight: 340,
    marginBottom: 12,
  },
  chatBubble: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    marginBottom: 8,
    maxWidth: "85%",
  },
  chatBubbleUser: {
    alignSelf: "flex-end",
    backgroundColor: COLORS.teal,
  },
  chatBubbleBot: {
    alignSelf: "flex-start",
    backgroundColor: "#F3EFE7",
  },
  chatBubbleText: {
    color: COLORS.ink,
    fontSize: FONT_SIZES.chat,
    lineHeight: 23,
  },
  chatBubbleTextUser: {
    color: "#fff",
  },
  chatInputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
  },
  chatStatus: {
    marginTop: 8,
    color: COLORS.inkSoft,
    fontSize: FONT_SIZES.helperText,
  },
  chatInput: {
    flex: 1,
    minHeight: 50,
    maxHeight: 120,
    borderWidth: 1.5,
    borderColor: COLORS.line,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#fff",
    fontSize: FONT_SIZES.chat,
  },
  chatSendButton: {
    backgroundColor: COLORS.teal,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    justifyContent: "center",
    minHeight: TOUCH.input,
  },
  chatSendButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: FONT_SIZES.formLabel,
  },
  confirmOverlay: {
    flex: 1,
    backgroundColor: "rgba(30, 43, 41, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  confirmCard: {
    backgroundColor: COLORS.card,
    borderRadius: 24,
    padding: 24,
    width: "100%",
    alignItems: "center",
  },
  confirmPhoto: {
    width: "100%",
    height: 280,
    borderRadius: 18,
    marginBottom: 16,
  },
  confirmNombre: {
    fontSize: FONT_SIZES.medName,
    fontWeight: "bold",
    color: COLORS.tealDark,
    textAlign: "center",
    marginBottom: 4,
  },
  confirmMensaje: {
    fontSize: FONT_SIZES.formLabel,
    color: COLORS.inkSoft,
    textAlign: "center",
    marginVertical: 16,
  },

  // Fila de acción por horario (una por cada toma del día de una medicina)
  doseRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F9F7F1",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.line,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginTop: 8,
    gap: 10,
  },
  doseRowTime: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  doseRowTimeText: {
    fontSize: FONT_SIZES.medDetail,
    color: COLORS.ink,
    fontWeight: "600",
  },
  doseRowButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 2,
    borderColor: COLORS.teal,
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    minHeight: 48,
  },
  doseRowButtonDone: {
    borderColor: COLORS.green,
    backgroundColor: COLORS.greenBg,
  },
  doseRowButtonText: {
    color: COLORS.teal,
    fontWeight: "bold",
    fontSize: FONT_SIZES.helperText,
  },
  doseRowButtonTextDone: {
    color: COLORS.green,
  },

  // Insignia de stock bajo
  stockBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
    backgroundColor: COLORS.amberBg,
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginTop: 8,
  },
  stockBadgeText: {
    color: COLORS.amberDark,
    fontWeight: "bold",
    fontSize: FONT_SIZES.helperText,
  },

  // Banner de aviso (permisos, estado del sistema)
  banner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: COLORS.amberBg,
    borderRadius: 16,
    padding: 14,
    marginTop: 14,
  },
  bannerOk: {
    backgroundColor: COLORS.greenBg,
  },
  bannerText: {
    flex: 1,
    color: COLORS.amberDark,
    fontSize: FONT_SIZES.helperText,
    lineHeight: 20,
  },
  bannerTextOk: {
    color: COLORS.green,
  },
  bannerButton: {
    backgroundColor: COLORS.amberDark,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  bannerButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: FONT_SIZES.helperText,
  },

  // Pantalla de Ajustes/Ayuda
  sectionTitle: {
    fontSize: FONT_SIZES.medName,
    fontWeight: "bold",
    color: COLORS.tealDark,
    marginBottom: 8,
  },
  paragraph: {
    color: COLORS.ink,
    fontSize: FONT_SIZES.helperText,
    lineHeight: 22,
    marginBottom: 8,
  },
  settingsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
  },
  settingsRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  settingsRowLabel: {
    fontSize: FONT_SIZES.medDetail,
    color: COLORS.ink,
    flexShrink: 1,
  },
  linkRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },

  // Historial de tomas
  historyDayTitle: {
    fontSize: FONT_SIZES.formLabel,
    fontWeight: "bold",
    color: COLORS.tealDark,
    marginTop: 18,
    marginBottom: 6,
  },
  historyItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: COLORS.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.line,
    padding: 12,
    marginBottom: 8,
  },
  historyItemTitle: {
    fontSize: FONT_SIZES.medDetail,
    color: COLORS.ink,
    fontWeight: "600",
  },
  historyItemSubtitle: {
    fontSize: FONT_SIZES.helperText,
    color: COLORS.inkSoft,
    marginTop: 2,
  },
});
