import { StyleSheet } from "react-native";

const COLORS = {
  bg: "#F5F3ED",
  card: "#FFFFFF",
  ink: "#1E2B29",
  inkSoft: "#4C5A57",
  teal: "#0F5C56",
  tealDark: "#0A413D",
  amber: "#E8873A",
  amberDark: "#C96A20",
  green: "#3F7D5C",
  line: "#E1DDD1",
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  header: {
    backgroundColor: COLORS.teal,
    paddingTop: 50,
    paddingBottom: 26,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    shadowColor: COLORS.tealDark,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
    zIndex: 10,
  },
  headerTitle: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 6,
  },
  headerSubtitle: {
    color: "#DDEFEA",
    fontSize: 15,
  },
  content: {
    flex: 1,
  },
  view: {
    padding: 16,
    paddingBottom: 100,
  },
  medName: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.tealDark,
    marginVertical: 4,
  },
  medDetail: {
    color: COLORS.inkSoft,
    fontSize: 14,
  },
  emptyBox: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.line,
    borderWidth: 2,
    borderStyle: "dashed",
    borderRadius: 22,
    padding: 30,
    alignItems: "center",
  },
  emptyBoxText: {
    color: COLORS.inkSoft,
    textAlign: "center",
    lineHeight: 22,
  },
  formCard: {
    backgroundColor: COLORS.card,
    borderRadius: 22,
    padding: 18,
    borderColor: COLORS.line,
    borderWidth: 1,
    marginTop: 14,
  },
  label: {
    fontWeight: "bold",
    color: COLORS.inkSoft,
    marginBottom: 6,
    marginTop: 14,
  },
  input: {
    backgroundColor: "#fff",
    borderWidth: 1.5,
    borderColor: COLORS.line,
    borderRadius: 14,
    padding: 14,
    fontSize: 16,
    color: COLORS.ink,
  },
  optionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  optionButton: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: COLORS.line,
    borderRadius: 14,
    padding: 12,
    alignItems: "center",
    backgroundColor: "#F9F7F1",
  },
  optionButtonActive: {
    backgroundColor: COLORS.teal,
    borderColor: COLORS.teal,
  },
  optionButtonText: {
    color: COLORS.inkSoft,
    fontWeight: "bold",
  },
  optionButtonTextActive: {
    color: "#fff",
  },
  buttonRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
  },
  smallButton: {
    flex: 1,
    marginTop: 0,
    marginBottom: 0,
  },
  btnPrimary: {
    backgroundColor: COLORS.teal,
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    marginTop: 20,
  },
  btnPrimaryText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  bottomNav: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    flexDirection: "row",
    borderTopWidth: 1,
    borderColor: COLORS.line,
    paddingBottom: 20,
    paddingTop: 10,
    shadowColor: COLORS.ink,
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 10,
  },
  navBtn: {
    flex: 1,
    alignItems: "center",
  },
  navIcon: {
    fontSize: 24,
    marginBottom: 4,
  },
  photoPreview: {
    width: "100%",
    height: 180,
    borderRadius: 14,
    marginTop: 10,
  },
  btnSecondary: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.teal,
    borderWidth: 2,
    borderRadius: 16,
    padding: 13,
    alignItems: "center",
    width: "100%",
    marginTop: 10,
    marginBottom: 16,
  },
  btnSecondaryText: {
    color: COLORS.teal,
    fontWeight: "bold",
    fontSize: 16,
  },
  btnDanger: {
    backgroundColor: COLORS.card,
    borderColor: "#C0392B",
    borderWidth: 2,
    borderRadius: 16,
    padding: 13,
    alignItems: "center",
  },
  btnDangerText: {
    color: "#C0392B",
    fontWeight: "bold",
    fontSize: 16,
  },
  btnDisabled: {
    backgroundColor: "#F0EEE7",
    borderColor: COLORS.line,
    opacity: 0.7,
  },
  btnDisabledText: {
    color: COLORS.inkSoft,
  },
  chatCard: {
    backgroundColor: COLORS.card,
    borderRadius: 22,
    padding: 16,
    borderColor: COLORS.line,
    borderWidth: 1,
    minHeight: 420,
  },
  chatTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.tealDark,
  },
  chatSubtitle: {
    color: COLORS.inkSoft,
    marginTop: 4,
    marginBottom: 12,
  },
  chatMessages: {
    maxHeight: 300,
    marginBottom: 12,
  },
  chatBubble: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    marginBottom: 8,
    maxWidth: "85%",
  },
  chatBubbleUser: {
    alignSelf: "flex-end",
    backgroundColor: COLORS.teal,
  },
  chatBubbleBot: {
    alignSelf: "flex-start",
    backgroundColor: "#F3EFE7",
  },
  chatBubbleText: {
    color: COLORS.ink,
    fontSize: 14,
    lineHeight: 20,
  },
  chatBubbleTextUser: {
    color: "#fff",
  },
  chatInputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
  },
  chatStatus: {
    marginTop: 8,
    color: COLORS.inkSoft,
    fontSize: 13,
  },
  chatInput: {
    flex: 1,
    minHeight: 46,
    maxHeight: 100,
    borderWidth: 1.5,
    borderColor: COLORS.line,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#fff",
  },
  chatSendButton: {
    backgroundColor: COLORS.teal,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    justifyContent: "center",
  },
  chatSendButtonText: {
    color: "#fff",
    fontWeight: "bold",
  },
});
